var count = 0;

function hell(callBack) {
	count++;
	alert(count + "回目:蝋人形にしてやろうかァ！");
	if (callBack)
		callBack();
}

hell(
	hell(
		hell(
			hell(
				hell(
					hell(
						hell(
							hell(
								hell(
									hell(
										hell(
											hell(
												hell(
													hell(
														hell(
															hell(
																hell(
																	hell(
																		hell(
																			hell(
																				hell(
																					hell(
																						hell(
																							hell(
																								hell(
																									hell(
																										hell(
																											hell(
																												hell(
																													hell(
																														hell(
																															hell(
																																hell(
																																	hell(
																																		hell(
																																			hell(
																																				hell(
																																					hell(
																																						hell(
																																							hell(
																																								hell(
																																									hell(
																																										hell(
																																											hell(
																																												hell(
																																													hell(
																																														hell(
																																															hell(
																																																hell(
																																																	hell(
																																																		hell(
																																																			hell(
																																																				hell(

																																																				)
																																																			)
																																																		)
																																																	)
																																																)
																																															)
																																														)
																																													)
																																												)
																																											)
																																										)
																																									)
																																								)
																																							)
																																						)
																																					)
																																				)
																																			)
																																		)
																																	)
																																)
																															)
																														)
																													)
																												)
																											)
																										)
																									)
																								)
																							)
																						)
																					)
																				)
																			)
																		)
																	)
																)
															)
														)
													)
												)
											)
										)
									)
								)
							)
						)
					)
				)
			)
		)
	)
);
